package aka.salako.morpion;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class TicTacToeController {

	// Event Listener on Button.onAction
	@FXML
	public void btnRestartClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
